site_name: Tarea 02

theme: 
  name: "material"
  features:
    - content.code.copy

plugins:
  - mkdocstrings
  - glightbox

nav:
  - index.md
  - tutorials.md
  - reference.md
  - explanation.md

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

